"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NODE_ENV = exports.DB_TEST_NAME = exports.SECRET_KEY = exports.DB_PORT = exports.DB_PASSWORD = exports.DB_USER = exports.DB_HOST = exports.DB_DEV_NAME = void 0;
require("dotenv/config");
exports.DB_DEV_NAME = process.env.DB_DEV_NAME || "";
exports.DB_HOST = process.env.DB_HOST || "";
exports.DB_USER = process.env.DB_USER || "";
exports.DB_PASSWORD = process.env.DB_PASSWORD || "";
exports.DB_PORT = process.env.DB_PORT;
exports.SECRET_KEY = process.env.SECRET_KEY || "";
exports.DB_TEST_NAME = process.env.DB_TEST_NAME || "";
exports.NODE_ENV = process.env.NODE_ENV;
